[package]
name = "awarder"
version = "0.1.0"
authors = ["Nechitelea Robert <robert.nechitelea@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.17"
yew-router = "0.14.0"
wasm-bindgen = "0.2.67"
serde = "1.0"